
/**************************************************************
 *	
 *	gongSFX, 8 bit, 11025Hz,
 *	1 channel, 32901 bytes/channel
 *	Total Size: 1 * 32901 + 4 (header) = 32945 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\galen\Dropbox\Public\Fall 2014\CS 2261\Projects\P04\gongSFX.wav
 *	Time-stamp: Tue Nov 04 20:16:13 2014
 *	
 **************************************************************/

#ifndef __GONGSFXH__
#define __GONGSFXH__

#define GONGSFXFREQ 11025
#define GONGSFXLEN 32901

extern const unsigned char gongSFX[32901];

#endif /* __GONGSFXH__ */
