
/**************************************************************
 *	
 *	introMusic, 8 bit, 11025Hz,
 *	1 channel, 169328 bytes/channel
 *	Total Size: 1 * 169328 + 4 (header) = 169372 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\galen\Dropbox\Public\Fall 2014\CS 2261\Projects\P04\introMusic.wav
 *	Time-stamp: Wed Nov 05 00:45:48 2014
 *	
 **************************************************************/

#ifndef __INTROMUSICH__
#define __INTROMUSICH__

#define INTROMUSICFREQ 11025
#define INTROMUSICLEN 169328

extern const unsigned char introMusic[169328];

#endif /* __INTROMUSICH__ */
