
/**************************************************************
 *	
 *	mainMusic, 8 bit, 22050Hz,
 *	1 channel, 338688 bytes/channel
 *	Total Size: 1 * 338688 + 4 (header) = 338732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\galen\Dropbox\Public\Fall 2014\CS 2261\Projects\P04\mainMusic.wav
 *	Time-stamp: Wed Nov 05 00:51:55 2014
 *	
 **************************************************************/

#ifndef __MAINMUSICH__
#define __MAINMUSICH__

#define MAINMUSICFREQ 22050
#define MAINMUSICLEN 338688

extern const unsigned char mainMusic[338688];

#endif /* __MAINMUSICH__ */
