
/**************************************************************
 *	
 *	slashSFX, 8 bit, 11025Hz,
 *	1 channel, 7378 bytes/channel
 *	Total Size: 1 * 7378 + 4 (header) = 7422 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\galen\Dropbox\Public\Fall 2014\CS 2261\Projects\P04\slashSFX.wav
 *	Time-stamp: Tue Nov 04 19:38:32 2014
 *	
 **************************************************************/

#ifndef __SLASHSFXH__
#define __SLASHSFXH__

#define SLASHSFXFREQ 11025
#define SLASHSFXLEN 7378

extern const unsigned char slashSFX[7378];

#endif /* __SLASHSFXH__ */
